/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#446275',
        'on-primary': '#ffffff',
        'primary-container': '#9cbbd0',
        'on-primary-container': '#2d4b5d',
        'primary-fixed': '#c7e7fd',
        'primary-fixed-dim': '#abcbe0',
        'on-primary-fixed': '#001e2d',
        'on-primary-fixed-variant': '#2c4a5c',
        'inverse-primary': '#abcbe0',

        secondary: '#615f50',
        'on-secondary': '#ffffff',
        'secondary-container': '#e7e3d0',
        'on-secondary-container': '#676556',
        'secondary-fixed': '#e7e3d0',
        'secondary-fixed-dim': '#cbc7b5',
        'on-secondary-fixed': '#1d1c11',
        'on-secondary-fixed-variant': '#49473a',

        tertiary: '#4c626b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a3bac4',
        'on-tertiary-container': '#354b53',
        'tertiary-fixed': '#cfe6f1',
        'tertiary-fixed-dim': '#b3cad4',
        'on-tertiary-fixed': '#071e26',
        'on-tertiary-fixed-variant': '#344a52',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        background: '#fbf9f8',
        'on-background': '#1b1c1c',
        surface: '#fbf9f8',
        'on-surface': '#1b1c1c',
        'surface-variant': '#e4e2e2',
        'on-surface-variant': '#42474c',
        'surface-dim': '#dbd9d9',
        'surface-bright': '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',

        outline: '#72787c',
        'outline-variant': '#c2c7cc',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-display': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        xl: '80px',
        'section-gap': '120px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
